Add appdata command
citra-emu/discord-bot pull request #116
Opened 2021-09-11 07:48 UTC by tree-png

Adds a command that sends a message to delete the yuzu folder in %localappdata%\yuzu and sends a link to the yuzu installer download page, feel free to change anything if necessary

2021-09-12 02:55 UTC, Moonlacer commented
YES TREE

2021-10-03 22:36 UTC, Schplee requested changes

2021-10-03 22:36 UTC, Schplee commented on src/responses/yuzu.json
> +      "appdata": { "reply": "Please try deleting the ``yuzu`` folder in ``%localappdata%/yuzu/`` and reinstall. Refer to the following guide if necessary: <https://yuzu-emu.org/wiki/faq/#yuzu-will-no
```suggestion
      "appdata": { "reply": "Please refer to the following guide to fully reinstall yuzu: <https://yuzu-emu.org/wiki/faq/#yuzu-will-not-update-further-or-starts-with-a-qt-platform-error>"},
```

2021-10-03 22:39 UTC, Schplee approved these changes

2021-10-03 22:39 UTC, merged