Add Dumping command
citra-emu/discord-bot pull request #167
Opened 2024-02-03 19:46 UTC by JaffaCat

This is a redo of PR 165, as that PR had several issues previously which should be fixed in this PR. 

This PR adds the .dumping command to Citra's Discord bot. By default anyone can use this command to inform users on what the process of dumping a game is.

_Suggested by SleepingSnake from the Citra Discord server._

2024-02-03 22:24 UTC, FearlessTobi requested changes

2024-02-03 22:24 UTC, FearlessTobi commented on citra.json
why is this file added?

2024-02-04 10:20 UTC, JaffaCat commented on citra.json
Because it needs to add the dumping command?

2024-02-04 10:41 UTC, sakuramipha commented on citra.json
Yes, it's the same as last time. You need to delete that file. It doesn't belong there, the only `citra.json` file you need is in `src/responses`

2024-02-04 10:47 UTC, JaffaCat commented on citra.json
Should be fixed now

2024-02-04 10:50 UTC, sakuramipha commented on citra.json
No, you deleted the wrong one. We want to keep `src/responses/citra.json` and delete `citra.json`

2024-02-04 11:09 UTC, JaffaCat commented on citra.json
Hopefully that was it. I cannot believe that there was a second citra.json in the code. That was such a simple fix

2024-02-04 12:36 UTC, sakuramipha commented on src/responses/citra.json
> +      "dumping": {"reply": "Dumping is the act of copying a game from your system/gamecart to an SD card. \nDumping is legal, however sharing the dumps with anyone else is piracy and thus is illegal.
```suggestion
      "dumping": {"reply": "Dumping is the act of creating an archival copy of your own legally purchased games. This process requires a hacked console to perform the dump \nDumping is legal, however sharing your dumped archival copies with anyone else is illegal."},
```
Clarifies on what dumping does, adds section about needing a console, clarifies what "dump" is when talking about the legality.

2024-02-04 23:37 UTC, JaffaCat commented on src/responses/citra.json
> +      "dumping": {"reply": "Dumping is the act of copying a game from your system/gamecart to an SD card. \nDumping is legal, however sharing the dumps with anyone else is piracy and thus is illegal.
Will change it later, I did originally have it set to something like that, but must have changed it unintentionally.

2024-02-05 13:55 UTC, sakuramipha approved these changes

2024-02-06 14:08 UTC, merged